[theme]
# Cor primária para elementos interativos
primaryColor="#0068C9"

# Cor de fundo principal da aplicação
backgroundColor="#F0F2F6"

# Cor de fundo para widgets e barras laterais
secondaryBackgroundColor="#FFFFFF"

# Cor do texto principal
textColor="#262730"

# Fonte para a aplicação
font="sans serif"
